"""empty message

Revision ID: e8117629ddae
Revises: c8a9a680ad66
Create Date: 2020-09-23 00:09:37.414918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8117629ddae'
down_revision = 'c8a9a680ad66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('commentstree')
    op.drop_table('comments')
    op.drop_table('blogtocatmap')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogtocatmap',
    sa.Column('blog_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cat_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('blog_id', 'cat_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blog_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name='comments_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('commentstree',
    sa.Column('ancestor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descendant', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ancestor'], ['comments.id'], name='commentstree_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant'], ['comments.id'], name='commentstree_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor', 'descendant'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
